// <auto-generated />
using System;
using DoAnSE104.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnSE104.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnSE104.Models.ChiSoDien", b =>
                {
                    b.Property<int>("MaDien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDien"));

                    b.Property<decimal>("GiaDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThangDien")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoDienCu")
                        .HasColumnType("int");

                    b.Property<int>("SoDienMoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDien");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiSoDien");
                });

            modelBuilder.Entity("DoAnSE104.Models.ChiSoNuoc", b =>
                {
                    b.Property<int>("MaNuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNuoc"));

                    b.Property<decimal>("GiaNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThangNuoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNuocCu")
                        .HasColumnType("int");

                    b.Property<int>("SoNuocMoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaNuoc");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiSoNuoc");
                });

            modelBuilder.Entity("DoAnSE104.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<int?>("HoaDonMaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("LoaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAnSE104.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Tiendichvu")
                        .HasColumnType("real");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DoAnSE104.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("KyHoaDon")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("MaDien")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<int>("MaNuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienPhatSinhKhac")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDien");

                    b.HasIndex("MaNguoiThue");

                    b.HasIndex("MaNuoc");

                    b.HasIndex("MaPhong");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAnSE104.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaNguoiThue");

                    b.HasIndex("MaPhong");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("DoAnSE104.Models.LichSuGiaDichVu", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("LichSuGiaDichVu");
                });

            modelBuilder.Entity("DoAnSE104.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("DoAnSE104.Models.NguoiThue", b =>
                {
                    b.Property<int>("MaNguoiThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiThue"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCongTac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNguoiThue");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NguoiThue");
                });

            modelBuilder.Entity("DoAnSE104.Models.NhaTro", b =>
                {
                    b.Property<int>("MaNhaTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaTro"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaChuTro")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhaTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhaTro");

                    b.HasIndex("MaChuTro");

                    b.ToTable("NhaTro");
                });

            modelBuilder.Entity("DoAnSE104.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("DiaChiPhong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("DienTich")
                        .HasColumnType("real");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaTro")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoNguoiHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex("MaNhaTro");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAnSE104.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaNguoiThue");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("DoAnSE104.Models.TrangThai", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("DoAnSE104.Models.User", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoAnSE104.Models.ChiSoDien", b =>
                {
                    b.HasOne("DoAnSE104.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnSE104.Models.ChiSoNuoc", b =>
                {
                    b.HasOne("DoAnSE104.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnSE104.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("DoAnSE104.Models.HoaDon", null)
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("HoaDonMaHoaDon");

                    b.HasOne("DoAnSE104.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAnSE104.Models.HoaDon", b =>
                {
                    b.HasOne("DoAnSE104.Models.ChiSoDien", "ChiSoDien")
                        .WithMany()
                        .HasForeignKey("MaDien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.ChiSoNuoc", "ChiSoNuoc")
                        .WithMany()
                        .HasForeignKey("MaNuoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiSoDien");

                    b.Navigation("ChiSoNuoc");

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnSE104.Models.HopDong", b =>
                {
                    b.HasOne("DoAnSE104.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnSE104.Models.LichSuGiaDichVu", b =>
                {
                    b.HasOne("DoAnSE104.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("DoAnSE104.Models.NguoiThue", b =>
                {
                    b.HasOne("DoAnSE104.Models.User", "NguoiDungTK")
                        .WithMany("DanhSachNguoiThue")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NguoiDungTK");
                });

            modelBuilder.Entity("DoAnSE104.Models.NhaTro", b =>
                {
                    b.HasOne("DoAnSE104.Models.User", "ChuTro")
                        .WithMany("DanhSachNhaTro")
                        .HasForeignKey("MaChuTro")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ChuTro");
                });

            modelBuilder.Entity("DoAnSE104.Models.Phong", b =>
                {
                    b.HasOne("DoAnSE104.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.NhaTro", "NhaTro")
                        .WithMany()
                        .HasForeignKey("MaNhaTro")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.TrangThai", "TrangThai")
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("NhaTro");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("DoAnSE104.Models.ThanhToan", b =>
                {
                    b.HasOne("DoAnSE104.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnSE104.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("DoAnSE104.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAnSE104.Models.User", b =>
                {
                    b.Navigation("DanhSachNguoiThue");

                    b.Navigation("DanhSachNhaTro");
                });
#pragma warning restore 612, 618
        }
    }
}
